services:
  postgres:
    image: postgres
    container_name: postgres_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432

volumes:
  postgres_data: