services:
  library-frontend:
    image: front-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    container_name: front-dev
    environment:
      - REACT_APP_BACKEND_URL_HTTP=http://localhost:8080/api/
      - REACT_APP_BACKEND_URL_WS=ws://localhost:8080/graphql/

  library-backend:
    image: back-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: back-dev
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: library-reverse-proxy
    depends_on:
      - library-backend
      - library-frontend
